### ISSUE TITLE
error message from honcho start

### ISSUE THREAD

**Issue by o9812** [devops-customers-18/customers#74]
__init__.py 
```
3:08:23 web.1  | [2018-11-12 23:08:23 +0000] [2475] [INFO] Starting gunicorn 19.9.0
23:08:23 web.1  | [2018-11-12 23:08:23 +0000] [2475] [INFO] Listening at: http://0.0.0.0:5000 (2475)
23:08:23 web.1  | [2018-11-12 23:08:23 +0000] [2475] [INFO] Using worker: sync
23:08:23 web.1  | [2018-11-12 23:08:23 +0000] [2479] [INFO] Booting worker with pid: 2479
23:08:23 web.1  | [2018-11-12 23:08:23 +0000] [2480] [INFO] Booting worker with pid: 2480
23:08:23 web.1  | [2018-11-12 23:08:23 +0000] [2479] [ERROR] Exception in worker process
23:08:23 web.1  | Traceback (most recent call last):
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
23:08:23 web.1  |     worker.init_process()
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 129, in init_process
23:08:23 web.1  |     self.load_wsgi()
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
23:08:23 web.1  |     self.wsgi = self.app.wsgi()
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
23:08:23 web.1  |     self.callable = self.load()
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
23:08:23 web.1  |     return self.load_wsgiapp()
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
23:08:23 web.1  |     return util.import_app(self.app_uri)
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 350, in import_app
23:08:23 web.1  |     __import__(module)
23:08:23 web.1  |   File "/vagrant/service/__init__.py", line 9, in <module>
23:08:23 web.1  |     from flask_restful import Api
23:08:23 web.1  | ImportError: No module named flask_restful
23:08:23 web.1  | [2018-11-12 23:08:23 +0000] [2479] [INFO] Worker exiting (pid: 2479)
23:08:23 web.1  | [2018-11-12 23:08:23 +0000] [2480] [ERROR] Exception in worker process
23:08:23 web.1  | Traceback (most recent call last):
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
23:08:23 web.1  |     worker.init_process()
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 129, in init_process
23:08:23 web.1  |     self.load_wsgi()
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
23:08:23 web.1  |     self.wsgi = self.app.wsgi()
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
23:08:23 web.1  |     self.callable = self.load()
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
23:08:23 web.1  |     return self.load_wsgiapp()
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
23:08:23 web.1  |     return util.import_app(self.app_uri)
23:08:23 web.1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 350, in import_app
23:08:23 web.1  |     __import__(module)
23:08:23 web.1  |   File "/vagrant/service/__init__.py", line 9, in <module>
23:08:23 web.1  |     from flask_restful import Api
23:08:23 web.1  | ImportError: No module named flask_restful
23:08:23 web.1  | [2018-11-12 23:08:23 +0000] [2480] [INFO] Worker exiting (pid: 2480)
23:08:23 web.1  | [2018-11-12 23:08:23 +0000] [2475] [INFO] Shutting down: Master
23:08:23 web.1  | [2018-11-12 23:08:23 +0000] [2475] [INFO] Reason: Worker failed to boot.
```

**Comment by slydomon** [comment]
Hi, I solved this one add push it on github
